const CHOICES = [
  [
    "Tend to have high average to genius intelligence, often (but not always) with significant splits between verbal and perceptual reasoning abilities, lower working memory and/or processing speeds, learning disabilities (for e.g., dyscalculia, dyslexia, reading comprehension)",
    "Superior long-term memory",
    "Weaker short-term memory",
    "May need academic accommodations in University",
    "A distinct learning profile consisting of a spikey profile of strengths and weaknesses, peaks and troughs, learning disabilities/differences",
    "Often have a rigid negative thinking, inflexible black or white thinking style or rigidity of thinking",
    "Context Blindness",
  ],
  [
    "May have dropped out of high school and gone back later or may have repeated a grade. May have unfinished or partial degrees, may have many finished degrees, many have Doctorate of Ph.D. level qualifications. Many have taken longer to achieve their education, as compared to their peers.",
    "May have a history of enrolling and attending university classes, followed by dropping out of classes or semesters. Sometime later, she then re-enrolls/attends later on, in life. This is usually due to being overloaded and overwhelmed. A history of deferring exams, not attending classes, dropping out of classes or programs, is common.",
    "May have repeated high school or courses OR dropped out completely.",
    "A history of many doctors and counselors visits throughout university life, without any significant improvement",
    "Difficulty taking the same amount of courses or classes as her peers",
    "May get lost on campus easily, lose possessions, be late for classes or exams",
  ],
  [
    "Often drawn to the helping, artistic or animal professions, and often an “expert” in her chosen field. I know of many Aspienwomen who are successful in the following careers: Artists, singers, actors, poets, writers, teachers, psychologists, psychiatrists, special needs teachers/consultants, horse trainers/whisperers, doctors, scientists, accountants, authors, childcare workers, models, comedians, artists, computer-related specialists, animal handlers or zookeepers, university professors, nurses, psychics/mediums, entrepreneurs and photographers.",
    "May miss days of work due to social exhaustion",
    "May find great difficulty attending/participating in staff meetings, lunch breaks, work social events",
    "May make up excuses for not attending work/staff functions",
    "May have a history of being unable to cope with work/employment environments, often moving from job to job, especially in younger adult years",
    "Hard-working conscientious worker",
    "May get stressed if have a lot of work to do in a short amount of time",
    "May become frustrated/stressed if asked to do too many things at once",
    "Tries very hard to avoid making mistakes, forgetting things",
    "Tries hard to please others",
    "May burn bridges (for e.g., walk out or quit jobs or relationships without notice)",
  ],
  [
    "May appear narcissistic, self-centered,  egocentric or caring only about her/himself due to not understanding the unwritten social rules",
    "Preference for one-on-one social interactions, single close friendships",
    "May obsess over one friend to the extreme",
    "Preference for friendships with men as they are easier to understand than women. They also find the interests of their peers boring and uninteresting",
    "Need more time away from people than their peers (solitude)",
    "May experience stress, anxiety, and confusion in social group or group work situations",
    "Social Anxiety leading to Social Phobia: Overanalyzing social interactions where they overthink (on a ‘loop’), about what they said, did, did not say, should have said or not said and what they wished they should have said. On the other side of this is continual stressing about what the other person is thinking of them. This is usually done to the extreme that it can be incapacitating for the person.",
    "Strong preference to engage in conversation related to their special interest",
    "Strong dislike for social chit-chat, gossip, nonsense, lies or conversation that lacks a ‘function’ to it, but some are known to engage in it themselves",
    "A history of being bullied, teased, left out and/or not fitting in with same-age peers unless she had/has similar “Aspie” friends",
    "An intense dislike of lies, but may lie to others herself. Many have admitted this to me.",
    "Has an ability to socialize, however, is unable to do so for long periods of time. Suffers from “social exhaustion” or a “social hangover” when socializing too much. The hangover can last hours to days, which can be debilitating",
    "Experience great difficulty with conflict, arguments, being yelled at, fighting, war, stress",
    "Has great difficulty asserting herself, asking for help, setting boundaries",
    "May need to drink or do drugs to be able to socialize, perform (sing), be with and/or around people",
    "May currently have or have experienced Post-Traumatic Stress, often due to being misunderstood, misdiagnosed, mistreated, and/or mismedicated.",
    "Social Skills differences – is exceptionally good one-on-one and presenting to groups, however, has difficulty working within group situations",
    "May find herself in social situations or relationships that she is unhappy with, but not know how to remove herself from them. Is highly at-risk for being with a toxic abusive person die to her nature. See ‘The Molotov Cocktail’ Series at http://www.vimeo.com/ondemand/femaleautism",
    "History of being taken advantage of by others, even though she has taken the appropriate business, legal or social advice from others",
    "Often bored in social situations or parties and/or does not know how to act in social situations",
    "May say “yes” to social events, then later make up an excuse as to why she cannot attend, often staying home in solitude (reading a book or engages in her special interest)",
    "Often prefers to be engaged in her special interest, rather than socializing",
    "May be considered the “black sheep” of the family",
    "Others consider her different, odd, eccentric or “weird” by others",
    "May feel like she has to act normal” to please others OR does not care at all about fitting in",
    "Copies, mimics, act in order to fit in and make others like her",
    "A people pleaser, but then may burn bridges suddenly (for e.g., quit relationships), as they have difficulty managing conflict, confrontation, and stress",
    "Females appear to be better than males at masking the traits of autism in social situations. However, girls are less able to do so in unfamiliar settings.",
    "May be considered a “loner” OR may have many acquaintances, but no real friends",
    "Social Naivety: may believe anything told to them by others (gossip, stories, jokes, and teasing), difficulty interpreting the intentions of others, misinterprets other peoples intentions, often jumping to conclusions about others, may be described as “gullible”",
  ],
  [
    "Difficulties communicating her thoughts and feelings, in words, to others, especially if anxious, stressed or upset. Often can type or write her thoughts much better",
    "May dislike asking others for help, be unable to ask or not know how to ask for help",
    "Maybe passive, not know how to assert her boundaries in a healthy manner",
    "May offend others by saying what she is thinking, even if she does not mean to; may appear aggressive or too intense",
    "May point out other people’s mistakes",
    "May give too much detail and end up boring others unintentionally",
    "May ask embarrassing questions (usually when younger)",
    "Unusual voice (flat, monotone, high-pitched, child-like)",
    "The tendency to take things literally, missing what people are trying to say",
    "May talk too loudly or too softly, often unaware that she is doing so",
    "May talk too much or not enough",
    "Often surprised when people tell her she has been rude or inappropriate",
    "Poor pragmatic language skills",
    "Struggle with eye contact and listening to someone at the same time",
    "May have auditory processing issues",
    "Struggles to understand non-verbal communication cues",
    "Often overshare in inappropriate ways, not understanding the steps to a friendship or relationship",
  ],
  [
    "Highly sensitivity, may not be able to listen to or watch the news, listen to the radio, read the newspaper, watch violent shows/movies or horror movies, see hurt or injured animals, abuse, war, trauma, are sensitive to the emotions and “emotional atmosphere” of the environment, experience referred emotion and psychic “6th sense” abilities, may have strong intuitive and/or psychic abilities",
    "May have sensory sensitivities in the following areas: hearing, vision, taste, touch, smell, balance, movement, intuition",
    "May be very sensitive to pain or have a high pain threshold",
    "May notice how food tastes or feels and one may be more important than the other",
    "May be clumsy or uncoordinated",
    "May dislike loud noises and/or be overwhelmed or stressed by bright lights, strong smells, coarse textures/clothing, sirens close by or people too close behind her.",
    "May find children hard to cope with due to crying, screaming or other loud noises",
    "Sensitive to the way clothes feel and how they may be more important than how they look",
    "May have to withdraw, isolate herself when overwhelmed by her senses",
    "May not be able to tolerate sounds, sights, smells, textures, a movement that she dislikes",
    "May not like to be hugged, cuddled or held. “I only like to hug if it’s my decision”",
    "Can get upset or distressed if unable to follow a familiar route when going somewhere",
    "Things that should feel painful may not be (bruises but not know how they got there, due to clumsiness)",
    "In social situations, the nervous system tends to be overwhelmed easily, leading to withdrawal (for e.g., wander off to a quiet spot at a party, play with children or animals)",
    "Strong hunger may be disrupting her mood and/or the ability to focus",
    "She may notice and enjoy delicate or fine scents, tastes, sounds, works of art, and pieces of music.",
    "Anxiety, stress and/or anger. Recent brain scanning research points towards the enlarged Amygdala’s role in intense emotions, anxiety, and anger",
    "May have auditory processing issues",
    "May have Irlen Syndrome",
    "May grind teeth or have lockjaw (anxiety)",
    "May have Obsessive Compulsive Disorder (OCD) or traits",
    "May have one or more of the 7 types of ADHD (see http://www.amenclinics.com)",
    "Usually has executive function difficulties (i.e., time management, planning ahead, organization)",
    "May rock, leg-bounce, fidget or other movements with hands, twirl hair, stroke soft fabric to self-soothe (aka stimming or self-soothing), doodle, draw",
    "May be very sensitive to medications, caffeine and/or alcohol",
    "May have gluten, wheat, casein or other food allergies/intolerances, gut issues",
    "May have sleep difficulties, a preference for staying up late at night, usually not a morning person, may be very creative at night",
    "May have Dyspraxia",
    "May have tics (for example, throat-clearing, coughing)",
  ],
  [
    "Usually dresses differently from her peers, often eccentric, may dress more for comfort than appearance.",
    "May dress “over the top” or unusually for occasions",
    "May try very hard to fit in appearance wise or may not care at all",
    "May have a special interest in fashion and femininity",
    "May not shower or upkeep hygiene at times, due to different priorities (usually being involved in special interests)",
    "Looks younger than her years",
    "Has an unusual voice; maybe “child-like”, monotone, loud or soft, quality to her voice",
    "Often does certain things with hands (twirling hair or items, different movements) or legs (leg “bouncing” or rocking while standing)",
  ],
  [
    "Books, computers, the Internet, animals, children, nature may be her best friends",
    "She loves quiet, solitude, peaceful surroundings",
    "She may be ultra-religious or not at all. Buddhism appears to be common",
    "May prefer to spend as much time as possible by herself, with animals or in nature",
    "May have a strong preference for routine and things being the same day after day",
    "Gets pleasure from being engaged in her chosen work and/or special interests",
    "She may make it a high priority to arrange her life, events, work, and environment to avoid overwhelming, stressful or upsetting situations",
  ],
  [
    "May date or marry much older or much younger partners, same-gender partner, tending not to see the “age”, “gender”, but rather the personality of the person first",
    "May be asexual, having preferences that are deemed as more important than sex or a relationship",
    "May be ‘hypersexual”, fascinated by physical sexual contact",
    "May differ from peers in terms of flexibility regarding sexual orientation or may think about or want to change gender. Some individuals may change gender or experiment with sexuality as a means to find social success or to “fit in” or feel less different",
    "May not have wanted or needed intimate relationships (asexual)",
    "There is a greater flexibility in sexuality and/or gender. Maybe heterosexual or may be asexual, gay, bisexual or transgender",
    "May be androgynous and prefer to wear men’s clothing",
    "As a teenager may experience Rapid Onset Gender Dysphoria (ROGD)",
    "May be or have a history of being promiscuous OR asexual or inappropriate (i.e., following someone they like although they don’t know how to engage in the art of dating or flirting. This can lead to stalking someone and eventually the Police becoming involved)",
    "Prone to safety issues due to not being aware of surroundings",
  ],
  [
    "Current research shows that individuals on the Spectrum do not have “restricted interests”, but rather a lifetime of interests that can vary. A special interest may involve the person’s career, Anime, fantasy (think Dr. Who, superheroes, and Harry Potter), just to name a few, writing, animals, reading, celebrities, food, fashion, jewelry, makeup, tattoos, symbols and TV Series (think Game of Thrones). This is not inclusive",
    "May attend ComicCon, SuperNova, love dressing up as a character.",
    "Ability to “hyperfocus” for long periods of time involved in the special interest, without eating, drinking or going to the toilet, is able to hyperfocus on her special interest for hours, often losing track of time",
    "Loves and revels in solitude, peace, and quiet. Solitude is often described as “needing it like the air I breathe”",
    "An intense love for nature and animals",
    "Often not interested in what other people find interesting",
    "May collect or hoard items of interest",
    "Introspection and self-awareness. Many women spend years trying to understand themselves, reading self-help and psychology books and wonder why they feel so different, from another planet or that the “Mothership has dropped me off on the wrong planet”.",
    "Justice Issues",
    "May know every lyric to a song or every line to a movie from repetitively watching them or listening to them",
  ],

  [
    "Feels things deeply (Category 5 emotions) and may be inconsolable (cannot be calmed down). Often has “over the top” reactions to events",
    "May have severe “depression attacks” that last for a few days; may feel the world is about to end",
    "Does not DO calm, stress, conflict, confrontation or fighting",
    "Struggles with degrees of emotions",
    "Think that people are laughing at her or making fun of her when they are not",
    "Facial expressions do not match the situation. May have an inappropriate emotional expression to the situation",
    "Other people’s moods affect her, especially if they are negative",
    "Tends to be very sensitive to emotional pain",
    "Emotions may be delayed so that for e.g., she can be a great ER doctor, but may fall apart a few days later about a traumatic work situation",
    "Anxiety is a constant from the very early years and is often overwhelmed by the amounts of tasks that need to be completed. Triggers for anxiety are varied from too much thinking to catastrophizing to change in routine, change in general, people, perfectionism, fear of failure, sensory issues, the feeling of not fitting in, the stress of feeling that he/she has to do things right, any environment that is noisy, has a lot of people in it, perceived or actual criticism",
    "Deeply moved by arts, music, certain movies",
    "May be unable to watch horror, violence, disturbing movies, and news programs",
    "Lives with continual generalized anxiety, bouts of depression that creep up on her",
    "Difficulty regulating emotions and managing stress",
    "Is socially and emotionally younger/immature than her chronological age, much younger if in her twenties",
    "Emotionally too honest (inability or difficulty hiding true feelings when it would be more socially acceptable to do so) and naive",
    "Experiences intense emotions of all kinds (for e.g. when she falls in love, she ‘falls’ in love deeply)",
    "May think she is being compassionate, but her actions may not come across that way",
    "Often too sensitive and possesses too much emotional empathy",
    "Usually, connect and/or are very sensitive to certain characters in movies",
    "Highly sensitive to issues affecting the earth, animals, people, advocacy, justice, human rights and the “underdog”",
    "Some women are quite “child-like”, not reaching a maturity until roughly 40 years of age",
    "Many create their own fantasy worlds",
  ],

  [
    "A natural born leader, independent, strong-willed, determined and can be highly competitive (even with herself)",
    "High levels of introversion OR can be extroverted",
    "Generally lack a strong sense of self, self-esteem and/or identity. May use chameleon-like skills to assimilate and be involved with to a variety of groups or different people over time, in a search for true identity.",
    "Has a high sense of justice and fairness, is a truth-seeker, sometimes to his/her own",
    "Highly creative and may have ‘rushes’ of original ideas",
    "Dislikes change and may find it disorienting and stressful",
    "Highly sensitive to criticism or perceived criticism",
    "Dislikes being observed when having to perform (performance anxiety)",
    "May have been told she cares too much, does too much for others and/or is too sensitive",
    "Is perfectionistic (may have attended a perfectionism group program)",
    "Attention to detail",
    "Obsessions/special interests can be short-term (switching from one to another quickly) or long-term (can make a great career)",
    "Naivety, innocence, trusting too much and taking others literally are a powerful concoction for being misused and abused",
    "Masking: giving off the illusion that everything is great or fine, when is it not. The mask often comes off at home with crying, meltdowns, or shutdowns.",
    "A strong sense of feeling different from her peers often described as being from a different planet",
    "May not have a sense of self and/or identity, self-esteem",
    "Tend to be very serious, often too serious at times",
    "Is intense in everything she does",
    "In childhood, may have been described as highly sensitive and/or shy",
    "Highly imaginative",
  ],
  [
    "May have trouble distinguishing between fantasy and reality",
    "Does not like it when people move or touch her belongings; people interpret her as rude and aggressive",
    "Past and/or current mental health history",
    "A history of self-harm",
    "May have a history of crying a lot, without knowing why",
    "May have a lengthy history of going to therapists, psychiatrists, psychologists",
    "May have tried a variety of medications",
    "Experiences social anxiety and generalized anxiety disorder or selective mutism",
    "May have Obsessive Compulsive Disorder or traits",
    "May have one or more of the 7 types of ADHD",
    "Has experienced ongoing depression and/or tiredness/exhaustion, without knowing why",
    "A history of trying to understand oneself, of finding answers to explain oneself and why she feels she is different or doesn’t fit in, as a woman",
    "A history of many doctors and counselors visits throughout university life",
    "May have a family history of Autism, Asperger Syndrome, Bi-polar disorder, schizophrenia, ADHD, OCD, anxiety disorders",
    "May have been misdiagnosed with bipolar disorder, borderline personality disorder or schizophrenia",
    "May have been previously diagnosed with anxiety disorder depression, an eating disorder, borderline personality disorder, bipolar disorder and/or ADHD",
    "A history of depression, anxiety, eating disorders, huge mood swings",
    "May have ROGD or be transgender",
  ],
  [
    "Compensatory Mechanisms are unfortunately what lead many an individual to receive a diagnosis much later in life when they cannot keep the mask on anymore.",
    "May have turned to alcohol, drugs, smoking in order to cope with intense emotions, self-medicate and/or socialize/fit in and/or be accepted with a group.",
    "May use a different persona when out in the public, in order to cope",
    "May have developed a variety of dysfunctional coping mechanisms (for example, arrogance and/or narcissism)",
    "May change gender or sexuality in an attempt to “fit in” and/or find the right group",
    "Has used imitation, social echolalia to pretend to be normal, fake it or pass for normal",
    "May rock standing up, lying down, in a rocking chair to calm down or self-soothe",
    "May need to withdraw into bed or a dark area or a place of solitude to gain privacy, quiet and manage sensory and/or social overload",
    "Withdrawal and/or Avoidance",
    "May have developed a personality disorder as a means of coping with Asperger Syndrome",
  ],
  [
    "Has the ability to feel other people emotions, take on the emotions of others",
    "May “know” or have knowledge of certain things, but no idea how she knows, aka “vibing”",
    "May be a professional psychic or medium",
    "Possesses one or more psychic abilities",
    "Is an “empath”",
    "Sensitive to other people’s negativity",
    "Often confused by the feelings she/he is having",
    "May take on the pain of other, aka Mirror-Touch Synaesthesia",
  ],
  [
    "May have perfect or relative perfect pitch",
    "Autodidactic – teaches herself",
    "Intelligence craves knowledge and loves learning",
    "Can teach herself just about anything she puts her mind too",
    "Has a strong will, is determined and independent",
    "Perfectionistic",
    "Have a remarkable long-term memory, photographic memory",
    "A great sense of humor",
    "Can work very well in a “crisis” situation",
    "Deeply reflective thinker",
    "Resilience, an ability to go from one crisis to another, to bounce back, to start again time and time again",
    "Attention to detail",
    "Great in one-on-one situations or presenting to a group",
    "More like “philosophers” than “professors, but can be both.",
    "Seeing in the “mind’s eye” exact details, gifted visual learner",
    "May be gifted with art, music, writing, languages, programming, acting, writing, editing, singing, an athlete",
    "May be highly intuitive",
    "Capable of deep philosophical thinking, females with Aspergers often become writers, vets, engineers, psychologists, social workers, psychiatrists, poets, artists, singers, performers, actresses, doctors, entrepreneurs or professors.",
  ],
  [
    "May be difficult to understand subtle emotions, for e.g., when someone is jealous or embarrassed, uninterested or bored",
    "Keeping up appearances, passing for normal",
    "Managing emotions and getting easily hurt by others; even if the other person was innocent",
    "Learning difficulties",
    "May get very upset with an unexpected change",
    "May not be able to tell when someone is flirting with her/him",
    "Challenging to work and function within a group",
    "Have a need for a highly controlled environment to sleep in",
    "Great difficulty and very sensitive to conflict, stress, arguments, fighting, wars, gossip and negativity, however ironically may engage in it",
    "Can be very negative and have catastrophic feelings; can be very self-deprecatory toward self",
    "Social-chit chat, small talk, conversation without a “function”, maintaining friendships and relationships, social anxiety or social phobia",
    "May like or prefer to be by herself as much as possible",
    "May find it challenging to understand what others expect of her",
    "Being taken advantage of due to naivety, innocence and trusting others too much; this often leads to being in toxic relationships or friendships",
    "Boundaries issues",
    "Executive function challenges: May have difficulty filling out forms, doing paperwork (completing taxes), budgeting money, finishing a task or job, planning (meals, the day, the week, answering the phone or talking to people on the phone, how to start a particular task and get it completed, knowing where their possessions are, going to appointments, waiting in line or at an appointment",
    "May have difficulty recognizing or remembering faces (prosopagnosia)",
    "May have Alexythymia: cannot verbalize their feelings as they are often unsure of what they are feeling",
    "May have Synaesthesia",
    "May experience existential dread",
    "Has difficulties with unexpected visitors just “dropping over”",
    "Gullibility or social naivity can get them into enormous trouble. Will often take at face value what a person says about another person",
    "Empathy May have a lack of cognitive empathy and hyper-empathy (for e.g., too much affective or sympathetic empathy)",
    "Cognitive Empathy: The ability to predict other’s thoughts and intentions, knowing how the other person feels and what they might be thinking. Also known as perspective-taking.",
    "Affective/Emotional Empathy: The ability or capacity to recognize emotions that are being experienced by another person, when you feel the feelings of another person along with the other person, as though their emotions are your own. Social neuroscience has found that this kind of empathy has to do with the mirror neuron system. Emotional empathy contributes to an individual being well-attuned to another person’s inner emotional world, an advantage for individuals in a wide range of careers from nursing to teaching to social work, psychology and other caring professions.",
    "Compassionate Empathy, or “empathic concern”. This kind of empathy helps us to understand a person’s predicament and feel with them, and also be spontaneously moved to help them, if and when others need help. Under stress, Theory of mind skills may appear to be completely absent.",
    "Sympathy: often has too much sympathy, placing her in danger, for example, I once had a young client who brought a homeless man home because, as she said, ” he had no hone”",
    "May have Ehlers-Danlos Syndrome, poor muscle tone, connective tissue disorder, double-jointed, fine and/or gross motor skill issues",
    "May have an intense desire to please others and/ be liked by others and be a “people pleaser”. May become highly distressed if she has the perception that someone does not like her or actually does not like her.",
    "Executive functioning difficulties may include: trouble making decisions, time management, planning ahead, organization, completing tasks.",
    "May have spent a lifetime of using enormous effort to socially “pretend”, “fake it”, “fit in”, “pass for normal”. May have utilized body language books, mirrors, acting/drama classes to improve social skills.",
    "May have tocophobia, the fear of childbirth or other fears (death, dying, a changing body, for example)",
    "May have gender dysphoria, also known as gender identity disorder (GID) dysphoria, and is a formal diagnosis for individuals who feel and experience significant stress and unhappiness with their birth gender and/or gender roles. These individuals are known as transsexual or transgender.",
    "Photographic visual memory",
    "An intense and continual need to figure oneself out.",
    "Hypermobility Syndrome",
    "Typical sex difference has been reported (i.e., female advantage), in relation to the “Reading the Mind in the Eyes” test (Eyes test), an advanced test of theory of mind.",
    "May be a high systemizer leading her to go into engineering or programming. High systemizing women see to feel the “weirdest” of the collective. May struggle with who she is gender-wise.",
  ],
];

module.exports = CHOICES;
